### ISSUE TITLE
Sync of name field and vibration lost

### ISSUE THREAD

**Issue by DavidStodolsky** [jcomeauictx/myturnb#31] opened 2017-07-04 19:01 UTC
A situation can develop where pressing the button transitions the vibration from once every 2 sec. to once a sec., but the name field continues to show "Waiting for new speaker." A name never appears in the field. (Others may not be pressing.)

Reloading of the page is necessary to recover proper function.
Often the reload results in a spinning gear and a warning that the name is already being used.
Reloading again can clear the issue and recover normal function.

Device: Samsung Note 4, Chrome browser, (4 participants?)

Also appears on the Mac with Chrome with the name of the the current speaker locked on (not Mac name). Pressing button caused darkening, but no other effect.

**Comment by DavidStodolsky** [comment] 2017-07-04 19:32
The screen can become unresponsive and the button locked on - my name is shown in the name field and is transmitted to the server. (Screen may dim slightly.) Pressing the button causes it to darken, but no other action is apparent.

Page reload may never completed. A second reload cleared the problem.



Device: Samsung Note 4, Chrome browser

**Comment by jcomeauictx** [comment] 2018-03-27 22:26
probably caused by race issues, which due to app design may not be solvable. should be fixed in the `pyturn` rewrite.

**Closed as completed by jcomeauictx** 2018-03-27 22:26 UTC
Labels: bug
